// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxolkbecfzspmoiszyvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4b2xrYmVjZnpzcG1vaXN6eXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzk3NzcsImV4cCI6MjA1NzcxNTc3N30.4VzeavkdeFa4fpyqYvNYKtswcVufVbO1ZW-Tv2qKwok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);